package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"plugin"
	"strconv"
	"strings"
	"syscall"

	"github.com/tavgar/JSMiner/internal/output"
	"github.com/tavgar/JSMiner/internal/proxy"
	"github.com/tavgar/JSMiner/internal/scan"
)

type headerSlice []string

func (h *headerSlice) String() string { return strings.Join(*h, ",") }
func (h *headerSlice) Set(v string) error {
	*h = append(*h, v)
	return nil
}

const version = "0.01v"

func main() {
	format := flag.String("format", "pretty", "output format: pretty or json")
	safe := flag.Bool("safe", false, "safe mode - only scan JS")
	allowFile := flag.String("allow", "", "allowlist file")
	rulesFile := flag.String("rules", "", "extra regex rules YAML")
	endpoints := flag.Bool("endpoints", false, "only return HTTP endpoints")
	posts := flag.Bool("posts", false, "only return HTTP POST request endpoints")
	external := flag.Bool("external", true, "follow external scripts and imports")
	render := flag.Bool("render", true, "render pages in headless Chrome")
	insecure := flag.Bool("insecure", true, "skip TLS certificate verification")
	longSecret := flag.Bool("longsecret", false, "detect generic long secrets")
	outFile := flag.String("output", "", "output file (stdout default)")
	quiet := flag.Bool("quiet", false, "suppress banner")
	proxyAddr := flag.String("proxy", "", "run as proxy on address (e.g., :8080)")
	crawl := flag.Bool("crawl", false, "crawl in-scope endpoints/paths discovered on each page to reach more JS and secrets")
	crawlDepth := flag.Int("crawl-depth", 2, "max link hops to follow beyond the seed page when -crawl is set")
	crawlAll := flag.Bool("crawl-all", false, "crawl to unlimited depth until no new in-scope pages remain (still bounded by -crawl-max-pages; pair with -crawl-max-pages 0 for no page cap)")
	crawlMaxPages := flag.Int("crawl-max-pages", 200, "max pages to fetch during a crawl (0 = unlimited)")
	crawlPermute := flag.Bool("crawl-permute", false, "reuse every discovered path under every discovered directory level (multiplies requests; capped by -crawl-permute-max)")
	crawlPermuteMax := flag.Int("crawl-permute-max", 1000, "max URLs generated by -crawl-permute (0 = unlimited)")
	methods := flag.String("methods", "", "comma-separated HTTP methods to probe each crawled URL with (default: GET,POST,PUT,PATCH,DELETE,OPTIONS)")
	noMethods := flag.Bool("no-methods", false, "disable multi-method probing / gathered-URL reporting during a crawl")
	noParamReplay := flag.Bool("no-param-replay", false, "disable replaying discovered parameters across every directory level during a crawl")
	noTemplateDedup := flag.Bool("no-template-dedup", false, "disable collapsing templated duplicate pages (/product/1 vs /product/2, paginated/faceted URLs) during a crawl")
	noWellKnown := flag.Bool("no-well-known", false, "disable seeding a crawl from the site's robots.txt and XML sitemaps")
	templateSampleMax := flag.Int("template-sample-max", 3, "max representative pages to crawl per templated class when template dedup is on")
	noSourceMaps := flag.Bool("no-source-maps", false, "disable recovering original source from JavaScript source maps advertised by scanned bundles")
	targetsFile := flag.String("targets", "", "file with list of targets")
	pluginsFlag := flag.String("plugins", "", "comma-separated plugin files")
	showSourceFlag := flag.Bool("show-source", false, "show source of each record (auto-enabled for multiple targets)")
	snippet := flag.Bool("snippet", false, "show a JS-prettified, syntax-highlighted code snippet around each finding")
	timeout := flag.Int("timeout", 8, "wait time in seconds for dynamic content to load when rendering pages (default: 8)")
	httpTimeout := flag.Int("http-timeout", 10, "per-request timeout in seconds for HTTP fetches (page/script fetches, calibration and method probes, sitemaps)")
	verbose1 := flag.Bool("v", false, "verbose: crawl narrative — matches per page, targets discovered, calibration/dedup skips")
	verbose2 := flag.Bool("vv", false, "more verbose: also log every HTTP request/response and page render (implies -v)")
	verbose3 := flag.Bool("vvv", false, "trace: also log per-target enqueue/skip, method probes, param replays and permutations (implies -vv)")
	exploreStates := flag.Int("explore-states", 12, "when rendering, max additional application states to reach through interaction — client-side navigation and filled/submitted forms (0 = render each page once)")
	rateLimit := flag.Float64("rate-limit", 0, "max HTTP requests per second across the scan (0 = no proactive limit; adaptive 429/503 backoff is always on)")
	chromePath := flag.String("chrome-path", "", "path to the Chrome/Chromium executable for rendering (default: auto-detect on PATH; also honours $JSMINER_CHROME)")
	downloadBrowser := flag.Bool("download-browser", false, "provision the bundled Chromium now (download if needed) and print its path, then exit if no target is given")
	noDownloadBrowser := flag.Bool("no-download-browser", false, "never download a Chromium; only use -chrome-path, a bundled or cached browser, or one on PATH")
	browserDest := flag.String("browser-dest", "", "with -download-browser, extract Chromium into <dir>/chromium so <dir> (binary + chromium/) ships as a self-contained bundle")
	var headerFlags headerSlice
	flag.Var(&headerFlags, "header", "HTTP header in 'Key: Value' format. May be repeated")
	flag.Parse()

	// handle flags placed after positional arguments
	args := flag.Args()
	leftover := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		a := args[i]
		if !strings.HasPrefix(a, "-") {
			leftover = append(leftover, a)
			continue
		}
		name := strings.TrimLeft(a, "-")
		parts := strings.SplitN(name, "=", 2)
		name = parts[0]
		switch name {
		case "endpoints":
			*endpoints = true
		case "posts":
			*posts = true
		case "render":
			val := "true"
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if b, err := strconv.ParseBool(val); err == nil {
				*render = b
			} else {
				*render = true
			}
		case "external":
			val := "true"
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if b, err := strconv.ParseBool(val); err == nil {
				*external = b
			} else {
				*external = true
			}
		case "safe":
			*safe = true
		case "longsecret":
			*longSecret = true
		case "quiet":
			*quiet = true
		case "v":
			*verbose1 = true
		case "vv":
			*verbose2 = true
		case "vvv":
			*verbose3 = true
		case "show-source":
			*showSourceFlag = true
		case "snippet":
			*snippet = true
		case "crawl":
			*crawl = true
		case "crawl-all":
			*crawlAll = true
		case "crawl-permute":
			*crawlPermute = true
		case "no-methods":
			*noMethods = true
		case "no-param-replay":
			*noParamReplay = true
		case "no-template-dedup":
			*noTemplateDedup = true
		case "no-well-known":
			*noWellKnown = true
		case "download-browser":
			*downloadBrowser = true
		case "no-download-browser":
			*noDownloadBrowser = true
		case "no-source-maps":
			*noSourceMaps = true
		case "methods":
			val := ""
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if val != "" {
				*methods = val
			}
		case "rate-limit":
			val := ""
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if f, err := strconv.ParseFloat(val, 64); err == nil {
				*rateLimit = f
			}
		case "crawl-depth", "crawl-max-pages", "crawl-permute-max", "template-sample-max":
			val := ""
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if n, err := strconv.Atoi(val); err == nil {
				switch name {
				case "crawl-depth":
					*crawlDepth = n
				case "crawl-max-pages":
					*crawlMaxPages = n
				case "template-sample-max":
					*templateSampleMax = n
				default:
					*crawlPermuteMax = n
				}
			}
		case "insecure":
			val := "true"
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if b, err := strconv.ParseBool(val); err == nil {
				*insecure = b
			} else {
				*insecure = true
			}
		case "timeout":
			val := ""
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if t, err := strconv.Atoi(val); err == nil {
				*timeout = t
			}
		case "http-timeout":
			val := ""
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if t, err := strconv.Atoi(val); err == nil {
				*httpTimeout = t
			}
		case "header":
			val := ""
			if len(parts) == 2 {
				val = parts[1]
			} else if i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") {
				val = args[i+1]
				i++
			}
			if val != "" {
				headerFlags = append(headerFlags, val)
			}
		case "format", "allow", "rules", "output", "targets", "plugins", "chrome-path", "browser-dest":
			if i+1 < len(args) {
				val := args[i+1]
				i++
				switch name {
				case "format":
					*format = val
				case "allow":
					*allowFile = val
				case "rules":
					*rulesFile = val
				case "output":
					*outFile = val
				case "targets":
					*targetsFile = val
				case "plugins":
					*pluginsFlag = val
				case "chrome-path":
					*chromePath = val
				case "browser-dest":
					*browserDest = val
				}
			}
		default:
			leftover = append(leftover, a)
		}
	}

	// Browser provisioning must be configured before any render (or an explicit
	// -download-browser) resolves a browser. An explicit -chrome-path wins;
	// otherwise fall back to $JSMINER_CHROME so a browser installed off PATH
	// (common in CI images and containers) is still used.
	if *chromePath == "" {
		*chromePath = os.Getenv("JSMINER_CHROME")
	}
	scan.SetChromePath(*chromePath)
	if *noDownloadBrowser {
		scan.SetAutoDownloadBrowser(false)
	}
	// Surface browser provisioning (chiefly the large first-run download) so the
	// scan does not appear to hang while Chromium downloads.
	if !*quiet {
		scan.BrowserNotice = func(msg string) { fmt.Fprintln(os.Stderr, "jsminer: "+msg) }
	}
	if *downloadBrowser {
		var (
			p   string
			err error
		)
		if *browserDest != "" {
			// Build a self-contained bundle: place chromium next to a copy of the
			// binary in <dir>/chromium.
			p, err = scan.ProvisionBundle(*browserDest)
		} else {
			p = scan.ResolveBrowser()
			if p == "" {
				err = fmt.Errorf("could not locate or download a Chromium for rendering")
			}
		}
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintln(os.Stderr, "browser: "+p)
		// Provision-only invocation: nothing else to do without a target.
		if len(leftover) == 0 && *targetsFile == "" && *proxyAddr == "" {
			os.Exit(0)
		}
	}

	var targets []string
	if *proxyAddr == "" && *targetsFile != "" {
		f, err := os.Open(*targetsFile)
		if err != nil {
			log.Fatal(err)
		}
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			t := strings.TrimSpace(sc.Text())
			if t == "" || strings.HasPrefix(t, "#") {
				continue
			}
			targets = append(targets, t)
		}
		if err := sc.Err(); err != nil {
			log.Fatal(err)
		}
		f.Close()
	}
	if *proxyAddr == "" {
		targets = append(targets, leftover...)
	}
	if *proxyAddr == "" && len(targets) == 0 {
		if !*quiet {
			fmt.Fprintln(os.Stderr, output.Banner(version))
		}
		fmt.Fprintln(os.Stderr, "usage: jsminer [URL|PATH|-] [flags]")
		os.Exit(2)
	}

	if *pluginsFlag != "" {
		for _, pl := range strings.Split(*pluginsFlag, ",") {
			pl = strings.TrimSpace(pl)
			if pl == "" {
				continue
			}
			if _, err := plugin.Open(pl); err != nil {
				log.Fatal(err)
			}
		}
	}

	if len(headerFlags) > 0 {
		h := http.Header{}
		for _, hv := range headerFlags {
			parts := strings.SplitN(hv, ":", 2)
			if len(parts) != 2 {
				continue
			}
			key := strings.TrimSpace(parts[0])
			val := strings.TrimSpace(parts[1])
			if key != "" {
				h.Add(key, val)
			}
		}
		scan.SetExtraHeaders(h)
	}

	// Set the render timeout if specified
	if *timeout > 0 {
		scan.SetRenderSleepDuration(*timeout)
	}
	scan.SetMaxExploreStates(*exploreStates)
	scan.SetSkipTLSVerification(*insecure)
	scan.SetHTTPTimeout(*httpTimeout)
	scan.SetRateLimit(*rateLimit)

	// -v/-vv/-vvv are cumulative: the highest one given wins, and each level
	// implies the ones below it.
	verbosity := 0
	if *verbose1 {
		verbosity = 1
	}
	if *verbose2 {
		verbosity = 2
	}
	if *verbose3 {
		verbosity = 3
	}
	scan.SetVerbosity(verbosity)

	// Provision the render browser up front (when rendering) so any first-run
	// Chromium download happens with a visible notice before scanning begins,
	// rather than silently stalling the first page render.
	if *render && *proxyAddr == "" && len(targets) > 0 {
		scan.WarmBrowser()
	}

	extractor := scan.NewExtractor(*safe, *longSecret)
	extractor.SetSnippet(*snippet)
	if *noSourceMaps {
		extractor.SetRecoverSourceMaps(false)
	}
	if *rulesFile != "" {
		if err := extractor.LoadRulesFile(*rulesFile); err != nil {
			log.Fatal(err)
		}
	}
	if *allowFile != "" {
		if err := extractor.LoadAllowlist(*allowFile); err != nil {
			log.Fatal(err)
		}
	}

	if *proxyAddr != "" {
		var out *os.File = os.Stdout
		if *outFile != "" {
			f, err := os.Create(*outFile)
			if err != nil {
				log.Fatal(err)
			}
			defer f.Close()
			out = f
		}
		printer := output.NewPrinter(*format, !*quiet, true, *snippet, version)
		ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer stop()
		if err := proxy.Run(ctx, *proxyAddr, extractor, printer, out, *endpoints); err != nil {
			log.Fatal(err)
		}
		return
	}

	var allMatches []scan.Match
	for _, target := range targets {
		var ms []scan.Match
		var err error

		if target == "-" {
			reader := bufio.NewReader(os.Stdin)
			if *posts {
				ms, err = extractor.ScanReaderPostRequests("stdin", reader)
				if err != nil {
					err = fmt.Errorf("failed to scan POST requests from stdin: %w", err)
				}
			} else {
				ms, err = extractor.ScanReaderWithEndpoints("stdin", reader)
				if err != nil {
					err = fmt.Errorf("failed to scan endpoints from stdin: %w", err)
				}
			}
		} else if isURL(target) {
			if *crawl {
				opts := scan.DefaultCrawlOptions()
				opts.MaxDepth = *crawlDepth
				if *crawlAll {
					opts.MaxDepth = -1
				}
				opts.MaxPages = *crawlMaxPages
				opts.Permute = *crawlPermute
				opts.PermuteMax = *crawlPermuteMax
				if *noMethods {
					opts.ProbeMethods = false
				}
				if *noParamReplay {
					opts.ParamReplay = false
				}
				if *noTemplateDedup {
					opts.TemplateDedup = false
				}
				if *noWellKnown {
					opts.DiscoverWellKnown = false
				}
				opts.TemplateSampleMax = *templateSampleMax
				if *methods != "" {
					var ms []string
					for _, m := range strings.Split(*methods, ",") {
						if m = strings.TrimSpace(m); m != "" {
							ms = append(ms, m)
						}
					}
					if len(ms) > 0 {
						opts.RequestMethods = ms
					}
				}
				// The level-0 progress lines are superseded by the richer -v/-vv/-vvv
				// output the scan package emits, so only install them when verbose
				// logging is off (and the banner isn't suppressed).
				if !*quiet && verbosity == 0 {
					opts.Progress = func(pageURL string, depth, pageNum int) {
						fmt.Fprintf(os.Stderr, "[crawl] (%d) depth %d %s\n", pageNum, depth, pageURL)
					}
					opts.OnCalibrated = func(n int) {
						fmt.Fprintf(os.Stderr, "[crawl] auto-calibration learned %d wildcard signature(s)\n", n)
					}
				}
				if *posts {
					ms, err = extractor.ScanURLPostsCrawl(target, *external, *render, opts)
					if err != nil {
						err = fmt.Errorf("failed to crawl POST requests from URL %s: %w", target, err)
					}
				} else {
					ms, err = extractor.ScanURLCrawl(target, *endpoints, *external, *render, opts)
					if err != nil {
						err = fmt.Errorf("failed to crawl endpoints from URL %s: %w", target, err)
					}
				}
			} else if *posts {
				ms, err = extractor.ScanURLPosts(target, *external, *render)
				if err != nil {
					err = fmt.Errorf("failed to scan POST requests from URL %s: %w", target, err)
				}
			} else {
				ms, err = extractor.ScanURL(target, *endpoints, *external, *render)
				if err != nil {
					err = fmt.Errorf("failed to scan endpoints from URL %s: %w", target, err)
				}
			}
		} else {
			f, err2 := os.Open(target)
			if err2 != nil {
				log.Printf("Error: failed to open file %s: %v", target, err2)
				continue
			}
			reader := bufio.NewReader(f)
			if *posts {
				ms, err = extractor.ScanReaderPostRequests(filepath.Base(target), reader)
				if err != nil {
					err = fmt.Errorf("failed to scan POST requests from file %s: %w", target, err)
				}
			} else {
				ms, err = extractor.ScanReaderWithEndpoints(filepath.Base(target), reader)
				if err != nil {
					err = fmt.Errorf("failed to scan endpoints from file %s: %w", target, err)
				}
			}
			f.Close()
		}

		if *posts {
			// A posts crawl harvests HTML markup links (as endpoint_url matches) to
			// follow the link graph; keep only POST endpoints and gathered URLs in the
			// output so those navigation-only links do not leak in.
			ms = scan.FilterPostMatches(ms)
		} else if *endpoints {
			// FilterEndpointMatches keeps only endpoint_* patterns; preserve the
			// crawl's gathered-URL findings, which are endpoint discoveries too.
			gathered := scan.FilterGatheredMatches(ms)
			ms = append(scan.FilterEndpointMatches(ms), gathered...)
		}

		if err != nil {
			log.Printf("Error processing %s: %v", target, err)
			continue
		}
		if len(ms) > 0 {
			allMatches = append(allMatches, ms...)
		}
	}

	allMatches = scan.UniqueMatches(allMatches)

	var out *os.File = os.Stdout
	if *outFile != "" {
		f, err := os.Create(*outFile)
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		out = f
	}

	showSource := *showSourceFlag || len(targets) > 1
	printer := output.NewPrinter(*format, !*quiet, showSource, *snippet, version)
	if err := printer.Print(out, allMatches); err != nil {
		log.Fatal(err)
	}

	if len(allMatches) > 0 {
		os.Exit(1)
	}
}

func isURL(s string) bool {
	return (len(s) > 7 && s[:7] == "http://") || (len(s) > 8 && s[:8] == "https://")
}
