package scan

import (
	"net/url"
	"path"
	"strings"
)

// CrawlOptions configures a breadth-first crawl seeded from a single URL.
//
// A crawl scans the seed page, harvests the endpoints it discovers
// (endpoint_url/endpoint_path and, for POST crawls, post_url/post_path),
// resolves the in-scope ones to absolute URLs and fetches them too, repeating
// until the depth or page budget is exhausted. Each fetched page is scanned
// with the normal rules, so crawling reaches JavaScript bundles — and the
// secrets in them — that are only linked from deeper pages or API responses.
type CrawlOptions struct {
	// MaxDepth is the number of link hops to follow beyond the seed page. A
	// depth of 0 scans only the seed (matching a plain ScanURL); 1 also scans
	// endpoints found on the seed, and so on. A negative value means unlimited
	// depth: the crawl follows links until the link graph is exhausted (or the
	// page budget/scope stops it), which is what -crawl-all requests.
	MaxDepth int

	// MaxPages caps the total number of pages fetched by the crawl, protecting
	// against runaway link graphs and parameterised URL explosions. Zero means
	// no cap (bounded only by MaxDepth and scope).
	MaxPages int

	// SameScopeOnly restricts crawling to the seed host and its subdomains (see
	// sameScope). Off-scope endpoints are still reported when they surface as
	// matches, they are simply not crawled. This is the expected default: the
	// user asked to follow discovered URLs only when they match the host.
	SameScopeOnly bool

	// Permute turns on cross-level path permutation: every discovered relative
	// path is reused under every directory level the crawl has seen, so a path
	// found in one place is also tried under all other levels (see permuter). It
	// is off by default because it multiplies requests; PermuteMax bounds it.
	Permute bool

	// PermuteMax caps the number of URLs generated by path permutation when
	// Permute is set. Zero means no cap (bounded only by MaxPages and scope).
	PermuteMax int

	// AutoCalibrate turns on ffuf-style auto-calibration: before crawling, the
	// target is probed with random paths to learn its catch-all/soft-404
	// fingerprint, and pages matching that fingerprint — or duplicating a page
	// already scanned — are skipped so the crawl stays on unique, useful pages.
	// It defaults to on (see DefaultCrawlOptions); the CLI always enables it and
	// exposes no toggle. The field is retained so library callers and tests can
	// opt out.
	AutoCalibrate bool

	// ProbeMethods turns on multi-method probing: every page the crawl visits is
	// requested with each verb in RequestMethods, and the verbs that work — judged
	// against the per-method, per-level error logic learned by auto-calibration —
	// are reported as a gathered-URL finding. It defaults to on (see
	// DefaultCrawlOptions) and is off in a zero-value CrawlOptions so library
	// callers and existing tests are unaffected.
	ProbeMethods bool

	// RequestMethods lists the HTTP methods used by ProbeMethods. Empty means the
	// default set (GET, POST, PUT, PATCH, DELETE, OPTIONS).
	RequestMethods []string

	// ParamReplay turns on cross-level parameter replay: parameter bodies
	// discovered on POST/PUT/PATCH endpoints are replayed against every directory
	// level the crawl has seen, and replays that work against a level's learned
	// per-method error logic are reported as gathered-URL findings. It requires
	// ProbeMethods and defaults to on (see DefaultCrawlOptions); ParamReplayMax
	// bounds it.
	ParamReplay bool

	// ParamReplayMax caps the number of (level, parameter) replays generated when
	// ParamReplay is set. Zero means no cap (bounded only by scope and the crawl).
	ParamReplayMax int

	// TemplateDedup collapses templated duplicate pages — pages that are
	// structurally the same and differ only in data, such as /product/1 vs
	// /product/2, paginated listings and calendar/faceted URLs — so the crawl
	// fetches only a representative few of each class instead of every instance,
	// spending its page budget on genuinely distinct pages. It works on two
	// levels: discovered URLs are grouped by a normalised URL template before they
	// are fetched (see templateClasser), so a suppressed instance costs no request
	// at all; and fetched pages are additionally grouped by a structural body
	// signature (see structuralSig), catching templated pages whose URLs do not
	// reveal the pattern. It defaults to on (see DefaultCrawlOptions) and is off in
	// a zero-value CrawlOptions so library callers and existing tests are
	// unaffected. TemplateSampleMax bounds how many representatives are kept.
	TemplateDedup bool

	// TemplateSampleMax caps how many representative pages are crawled from each
	// template class when TemplateDedup is set. Zero selects a sensible default
	// (defaultTemplateSampleMax).
	TemplateSampleMax int

	// Progress, when non-nil, is invoked once per fetched page with the page
	// URL, its depth from the seed and the running page count. It lets the CLI
	// surface crawl progress without the scan package depending on the output
	// layer.
	Progress func(pageURL string, depth, pageNum int)

	// OnCalibrated, when non-nil, is invoked once after auto-calibration with
	// the number of wildcard signatures learned.
	OnCalibrated func(wildcardSigs int)
}

// DefaultCrawlOptions returns sensible defaults for interactive use: follow two
// hops beyond the seed, stay on the seed host, stop after 200 pages and
// auto-calibrate to suppress catch-all/soft-404 and duplicate pages.
func DefaultCrawlOptions() CrawlOptions {
	return CrawlOptions{
		MaxDepth: 2, MaxPages: 200, SameScopeOnly: true, AutoCalibrate: true,
		ProbeMethods: true, RequestMethods: defaultRequestMethods(),
		ParamReplay: true, ParamReplayMax: 500,
		TemplateDedup: true, TemplateSampleMax: defaultTemplateSampleMax,
	}
}

// templateSampleMax returns the per-class representative cap to use for a crawl,
// falling back to the default when the option is left unset.
func templateSampleMax(opts CrawlOptions) int {
	if opts.TemplateSampleMax > 0 {
		return opts.TemplateSampleMax
	}
	return defaultTemplateSampleMax
}

// crawlTarget is a queued page together with its distance from the seed.
type crawlTarget struct {
	url   string
	depth int
}

// ScanURLCrawl scans urlStr and then crawls the in-scope endpoints it
// discovers, returning the deduplicated union of all matches. When endpoints is
// true only endpoint matches are produced (as with ScanURL). external controls
// whether off-scope script/import references are followed while scanning an
// individual page; the page-to-page crawl itself is governed by opts.
func (e *Extractor) ScanURLCrawl(urlStr string, endpoints, external, render bool, opts CrawlOptions) ([]Match, error) {
	scanPage := func(u, baseHost string, visited map[string]struct{}) ([]Match, error) {
		return e.scanURL(u, baseHost, endpoints, visited, external, render)
	}
	return e.crawlBFS(urlStr, opts, scanPage)
}

// ScanURLPostsCrawl behaves like ScanURLCrawl but scans each page for HTTP POST
// request endpoints, following the discovered endpoints to reach deeper pages.
func (e *Extractor) ScanURLPostsCrawl(urlStr string, external, render bool, opts CrawlOptions) ([]Match, error) {
	scanPage := func(u, baseHost string, visited map[string]struct{}) ([]Match, error) {
		return e.scanURLPosts(u, baseHost, visited, external, render)
	}
	return e.crawlBFS(urlStr, opts, scanPage)
}

// crawlBFS drives the breadth-first crawl. scanPage scans a single page (and,
// via scanURL/scanURLPosts, its script/import graph) and returns its matches;
// crawlBFS harvests fresh in-scope targets from those matches and keeps going.
//
// The visited map is shared across every scanPage call so a JS bundle
// referenced from many pages is fetched and scanned only once. The enqueued map
// tracks page-level targets so each page is crawled at most once.
func (e *Extractor) crawlBFS(seedURL string, opts CrawlOptions, scanPage func(u, baseHost string, visited map[string]struct{}) ([]Match, error)) ([]Match, error) {
	seed, err := url.Parse(seedURL)
	if err != nil {
		return nil, err
	}
	baseHost := seed.Hostname()

	origin := seed.Scheme + "://" + seed.Host

	var perm *permuter
	if opts.Permute {
		perm = newPermuter(origin, baseHost, opts.PermuteMax)
	}

	// A single calibrator backs both whole-page auto-calibration (skipPage) and
	// per-method probing, so the two share the level fingerprints they learn. It
	// is created whenever either feature is active.
	var cal *autoCalibrator
	if opts.AutoCalibrate || opts.ProbeMethods {
		cal = newAutoCalibrator()
		cal.setBase(seed.String())
	}
	if opts.AutoCalibrate {
		// Structural body dedup rides on the calibrator, which is only installed
		// (and consulted by skipPage) when auto-calibration is active.
		if opts.TemplateDedup {
			cal.enableStructuralDedup(templateSampleMax(opts))
		}
		n := cal.calibrate(seed.String())
		e.SetCalibrator(cal)
		defer e.SetCalibrator(nil)
		if opts.OnCalibrated != nil {
			opts.OnCalibrated(n)
		}
	}

	methods := normalizeMethods(opts.RequestMethods)
	var replay *paramReplayer
	if opts.ProbeMethods && opts.ParamReplay {
		replay = newParamReplayer(origin, opts.ParamReplayMax)
	}

	// The template classer groups discovered URLs by page template and admits only
	// a representative few of each, so /product/1…/product/N and paginated or
	// faceted URLs do not each consume a fetch and a slot in the page budget.
	var classer *templateClasser
	if opts.TemplateDedup {
		classer = newTemplateClasser(templateSampleMax(opts))
	}

	visited := make(map[string]struct{})
	enqueued := make(map[string]struct{})

	start := normalizeCrawlURL(seed.String())
	queue := []crawlTarget{{url: start, depth: 0}}
	enqueued[start] = struct{}{}
	// The seed is always crawled; register it so it counts toward its own class.
	classer.admit(start)

	var all []Match
	pages := 0
	for len(queue) > 0 {
		if opts.MaxPages > 0 && pages >= opts.MaxPages {
			break
		}
		t := queue[0]
		queue = queue[1:]
		pages++
		if opts.Progress != nil {
			opts.Progress(t.url, t.depth, pages)
		}

		ms, err := scanPage(t.url, baseHost, visited)
		if err != nil {
			continue
		}
		all = append(all, ms...)

		// Report which request methods this page accepts, judged against the
		// per-method error logic learned for its level.
		if opts.ProbeMethods {
			if worked := probeURLMethods(cal, t.url, methods, ""); worked != nil {
				if gm, ok := gatheredMatch(t.url, worked, ""); ok {
					all = append(all, gm)
				}
			}
		}

		// A negative MaxDepth means unlimited depth, so only the page budget and
		// scope bound the crawl; otherwise stop harvesting once the cap is hit.
		if opts.MaxDepth >= 0 && t.depth >= opts.MaxDepth {
			continue
		}
		targets := crawlTargetsFromMatches(ms, t.url, baseHost, opts)

		// Replay parameters discovered on this page against every level seen so
		// far, and this page's levels against every parameter seen so far; keep
		// the replays that work against each level's learned per-method logic.
		if replay != nil {
			// Include this page's own URL so its directory level is registered even
			// when nothing under it was discovered as a crawl target.
			levelURLs := make([]string, 0, len(targets)+1)
			levelURLs = append(levelURLs, targets...)
			levelURLs = append(levelURLs, t.url)
			for _, rt := range replay.observe(paramsFromMatches(ms), levelURLs) {
				worked := probeURLMethods(cal, rt.url, methods, rt.params)
				if gm, ok := gatheredMatch(rt.url, worked, rt.params); ok {
					all = append(all, gm)
				}
			}
		}
		for _, next := range targets {
			if _, ok := enqueued[next]; ok {
				continue
			}
			if !classer.admit(next) {
				continue
			}
			enqueued[next] = struct{}{}
			queue = append(queue, crawlTarget{url: next, depth: t.depth + 1})
		}
		// Cross-level permutation reuses every path discovered so far under every
		// level seen so far, enqueuing the fresh combinations at the next depth.
		if perm != nil {
			for _, next := range perm.observe(targets) {
				if _, ok := enqueued[next]; ok {
					continue
				}
				if !classer.admit(next) {
					continue
				}
				enqueued[next] = struct{}{}
				queue = append(queue, crawlTarget{url: next, depth: t.depth + 1})
			}
		}
	}

	return UniqueMatches(all), nil
}

// crawlTargetsFromMatches derives the next set of crawlable page URLs from the
// matches found on pageURL. Endpoint, POST and `path` values are resolved
// against the page URL, filtered to http(s), optionally constrained to the seed
// scope and stripped of obvious binary assets that would waste a fetch. `path`
// matches are included so that genuine paths surfaced by the power rule (not
// just JS endpoints) are followed too; they have already passed validPathMatch,
// and non-web values such as Windows paths fall out at the scheme check below.
func crawlTargetsFromMatches(ms []Match, pageURL, baseHost string, opts CrawlOptions) []string {
	seen := make(map[string]struct{})
	var out []string
	for _, m := range ms {
		switch m.Pattern {
		case "endpoint_url", "endpoint_path", "post_url", "post_path", "path":
		default:
			continue
		}
		// `path` values retain a leading space from the rule's `(?:^|\s)` anchor;
		// trim before resolving so the reference parses correctly.
		raw := strings.TrimSpace(m.Value)
		if raw == "" {
			continue
		}
		abs := resolveURL(pageURL, raw)
		u, err := url.Parse(abs)
		if err != nil {
			continue
		}
		if u.Scheme != "http" && u.Scheme != "https" {
			continue
		}
		if opts.SameScopeOnly && !sameScope(baseHost, u.Hostname()) {
			continue
		}
		if !crawlableTarget(u) {
			continue
		}
		n := normalizeCrawlURL(u.String())
		if _, ok := seen[n]; ok {
			continue
		}
		seen[n] = struct{}{}
		out = append(out, n)
	}
	return out
}

// normalizeCrawlURL canonicalises a URL for crawl bookkeeping by dropping the
// fragment, which never changes what the server returns. The query is retained
// because it can select a distinct resource; the page budget bounds any
// parameter explosion.
func normalizeCrawlURL(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return raw
	}
	u.Fragment = ""
	return u.String()
}

// nonCrawlableExts are asset types that cannot yield further JavaScript,
// endpoints or secrets, so fetching them during a crawl is pure overhead.
var nonCrawlableExts = map[string]struct{}{
	".png": {}, ".jpg": {}, ".jpeg": {}, ".gif": {}, ".svg": {}, ".webp": {},
	".ico": {}, ".bmp": {}, ".tiff": {},
	".woff": {}, ".woff2": {}, ".ttf": {}, ".eot": {}, ".otf": {},
	".mp4": {}, ".webm": {}, ".mp3": {}, ".wav": {}, ".ogg": {}, ".avi": {},
	".mov": {}, ".mkv": {},
	".zip": {}, ".gz": {}, ".tar": {}, ".rar": {}, ".7z": {}, ".bz2": {},
	".pdf": {}, ".doc": {}, ".docx": {}, ".xls": {}, ".xlsx": {}, ".ppt": {},
	".pptx": {},
}

// crawlableTarget reports whether u is worth fetching during a crawl. Binary
// assets (images, fonts, media, archives, documents) are skipped; everything
// else — HTML pages, JS, JSON, extensionless routes and API paths — is kept.
func crawlableTarget(u *url.URL) bool {
	ext := strings.ToLower(path.Ext(u.Path))
	if ext == "" {
		return true
	}
	_, skip := nonCrawlableExts[ext]
	return !skip
}
